### 상품 추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJIYnpVcjZ3NS84OVk3dlZhWW5IVWI1Ulk1RExQV2trOVFYejFlUzY1QnBVPSIsImp0aSI6IlF0WENYOWs4RVdNeER0a0lBSmJ1MkE9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAzNTYzMDksImV4cCI6MTY4MDQ0MjcwOX0.3HIONMTLhofpdU1N3mVj6D4a9DrLqzEPm55SRtcIxa0


{
  "description": "유저 등록 ",
  "items": [
    {
      "count": 1,
      "name": "300",
      "price": 100000
    }
  ],
  "name": "나이키2"
}

### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJIYnpVcjZ3NS84OVk3dlZhWW5IVWI1Ulk1RExQV2trOVFYejFlUzY1QnBVPSIsImp0aSI6IlF0WENYOWs4RVdNeER0a0lBSmJ1MkE9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAzNTYzMDksImV4cCI6MTY4MDQ0MjcwOX0.3HIONMTLhofpdU1N3mVj6D4a9DrLqzEPm55SRtcIxa0

{
  "productId": 8,
  "count": 1,
  "name": "50",
  "price": 200000
}

### 상품 수정
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJIYnpVcjZ3NS84OVk3dlZhWW5IVWI1Ulk1RExQV2trOVFYejFlUzY1QnBVPSIsImp0aSI6IlF0WENYOWs4RVdNeER0a0lBSmJ1MkE9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAzNTYzMDksImV4cCI6MTY4MDQ0MjcwOX0.3HIONMTLhofpdU1N3mVj6D4a9DrLqzEPm55SRtcIxa0


{
  "description": "상품 설명 변경",
  "items": [
    {
      "id": 7,
      "count": 1,
      "name": "400",
      "price": 200000
    }
  ],
  "id": 6,
  "name": "나이키2"
}

### 상품 아이템 수정
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJIYnpVcjZ3NS84OVk3dlZhWW5IVWI1Ulk1RExQV2trOVFYejFlUzY1QnBVPSIsImp0aSI6IlF0WENYOWs4RVdNeER0a0lBSmJ1MkE9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAzNTYzMDksImV4cCI6MTY4MDQ0MjcwOX0.3HIONMTLhofpdU1N3mVj6D4a9DrLqzEPm55SRtcIxa0

{
  "id": 15,
  "count": 100,
  "name": "50000",
  "price": 200000
}

### 상품 삭제
DELETE http://localhost:8082/seller/product?id=8
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJIYnpVcjZ3NS84OVk3dlZhWW5IVWI1Ulk1RExQV2trOVFYejFlUzY1QnBVPSIsImp0aSI6IlF0WENYOWs4RVdNeER0a0lBSmJ1MkE9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAzNTYzMDksImV4cCI6MTY4MDQ0MjcwOX0.3HIONMTLhofpdU1N3mVj6D4a9DrLqzEPm55SRtcIxa0


### 상품 아이템 삭제
DELETE http://localhost:8082/seller/product/item?id=14
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJIYnpVcjZ3NS84OVk3dlZhWW5IVWI1Ulk1RExQV2trOVFYejFlUzY1QnBVPSIsImp0aSI6IlF0WENYOWs4RVdNeER0a0lBSmJ1MkE9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAzNTYzMDksImV4cCI6MTY4MDQ0MjcwOX0.3HIONMTLhofpdU1N3mVj6D4a9DrLqzEPm55SRtcIxa0

### 상품 검색
GET http://localhost:8082/search/product?name=나이키
Content-Type: application/json

### 상품 상세정보
GET http://localhost:8082/search/product/detail?productId=2